[tool.poetry]
name = "vrtoolpreprocess"
version = "0.1.0"
description = ""
authors = ["WJKlerk <61802340+WJKlerk@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.10"
geopandas = "^0.12.2"
pandas = "^2.0.0"
Fiona = "^1.9.2"
jupyterlab = "^3.6.3"
OWSLib = "^0.28.1"
numpy = "^1.24.2"
shapely = "^2.0.1"
openpyxl = "^3.1.2"
seaborn = "^0.12.2"
requests = "^2.28.2"
scipy = "^1.10.1"
geojson = "^3.0.1"
charset-normalizer = "^3.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
