name: vr_preprocessing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::fiona
  - conda-forge::jupyterlab
  - conda-forge::poetry=1.3.2
  - pip:
    - vrtool @ git+https://github.com/Deltares/Veiligheidsrendement.git@feature/VRTOOL-69_implement_database_orm